---
- name: See if Dock item exists {{ dock_add_item.name | default(dock_add_item) }}.
  ansible.builtin.command:
    cmd: "dockutil --find '{{ dock_add_item.name }}'"
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  changed_when: false
  tags: ['dock']

- name: Get current dock section from output.
  ansible.builtin.set_fact:
    current_section: "{{ dockitem_exists.stdout | regex_replace('^.*was found in (.*) at slot.*$', '\\1') }}"
  when: dockitem_exists.rc == 0
  tags: ['dock']

- name: Ensure Dock item exists {{ dock_add_item.name | default(dock_add_item) }}.
  ansible.builtin.command:
    cmd: "dockutil --add '{{ dock_add_item.path }}' --label '{{ dock_add_item.name }}'"
  when: dockitem_exists.rc >0 or
        dockitem_exists.rc == 0 and current_section == 'recent-apps'
  tags: ['dock']

- name: Pause for 7 seconds between dock changes.
  ansible.builtin.pause:
    seconds: 7
  when: dockitem_exists.rc >0 or
        dockitem_exists.rc == 0 and current_section == 'recent-apps'
  tags: ['dock']
